---
- name: "configuration play."
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  # environment:
  # Add more env vars here
  task:
    - name: "Test"
      become: yes
      shell: git --version
    - name: "Stop docker"
      become: yes
      shell: docker-compose down
    - name: "Start docker"
      become: yes
      shell: docker-compose up -d
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
