name: Main

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}


jobs:

  test_admin:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/admin

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run the tests
      run: npm ci
      
    - name: Build
      run: npm run build --if-present
      
    - name: test
      run: npm test
  

  build_and_push_to_registry_admin:

    name: Build and push to Docker Hub

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/admin

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}          
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            
      - name: Get Current Date 
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

      - name: Build, Tag and Push Frontend Image
        run: |
          docker build . --file Dockerfile -t $DOCKERHUB_USERNAME/realxchangeadmin:${{ steps.date.outputs.date }}
          docker push $DOCKERHUB_USERNAME/realxchangeadmin:${{ steps.date.outputs.date }}
        

  test_client:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ../client

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run the tests
      run: npm ci
      
    - name: Build
      run: npm run build --if-present
      
    - name: test
      run: npm test


  build_and_push_to_registry_client:

    name: Build and push to Docker Hub

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ../client

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}          
          password: ${{ secrets.DOCKERHUB_TOKEN }}
            
      - name: Get Current Date 
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

      - name: Build, Tag and Push Frontend Image
        run: |
          docker build . --file Dockerfile -t $DOCKERHUB_USERNAME/realxchangeclient:${{ steps.date.outputs.date }}
          docker push $DOCKERHUB_USERNAME/realxchangeclient:${{ steps.date.outputs.date }}                          
  